### ISSUE TITLE
Health Check Warning and Regression Degradation

### ISSUE THREAD

**Issue by andyday** [Nordstrom/xrpc#134]
Per @xjdr 

i am starting to see this error throw every so often now
we also appear to added a bit of a speed regression somewhere is the last few commits
small one, but it appears to be consistent

```
15215088 [xrpc-worker-0] WARN  c.c.m.h.HealthCheckRegistry - Error executing health check simple
io.netty.util.concurrent.BlockingOperationException: PromiseTask@600f6080(incomplete, task: com.codahale.metrics.health.HealthCheckRegistry$1@63103e65)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:391)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:226)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:34)
    at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
    at com.codahale.metrics.health.HealthCheckRegistry.runHealthChecks(HealthCheckRegistry.java:193)
    at com.nordstrom.xrpc.server.Router.lambda$scheduleHealthChecks$0(Router.java:134)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:131)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:273)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by andyday** [comment]
@xjdr do you see this warning during regression only or at other times?

**Comment by andyday** [comment]
nvm.  i see it now...  it happens while its running idle...
