### ISSUE TITLE
Fix NPE for health checks at startup

### ISSUE THREAD

**Issue by xjdr** [Nordstrom/xrpc#50]
There is currently an NPE that is thrown at startup when the health checks are being scheduled against a worker thread pool that doesn't exist yet. This issue is being filed to fix that bug as well as simplify the invocation of the admin handlers. 

```java
Exception in thread "main" java.lang.NullPointerException
	at com.nordstrom.xrpc.server.Router.scheduleHealthChecks(Router.java:130)
	at com.nordstrom.xrpc.server.Router.scheduleHealthChecks(Router.java:126)
	at com.nordstrom.xrpc.demo.Example.main(Example.java:156)
```

**Comment by xjdr** [comment]
Addressed by 3d018e532b8142d8dc7c5415a0da09d5d686b566
